LibriClassroom/Controllers/CourseManagerController.cs
using Google;
using Google.Apis.Auth.OAuth2;
using Google.Apis.Auth.OAuth2.Mvc;
using Google.Apis.Classroom.v1;
using Google.Apis.Classroom.v1.Data;
using Google.Apis.Requests;
using Google.Apis.Services;
using LibriClassroom.Models;
using LibriClassroom.Models.Entities;
using LibriClassroom.ViewModels;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Security.Claims;
using System.Security.Cryptography.X509Certificates;
using System.Threading;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using System.Data;
using Newtonsoft.Json;
using System.Text;
using Google.Apis.Drive.v2;

namespace LibriClassroom.Controllers
{
    public class CourseManagerController : Controller
    {

        private static DataClasses1DataContext db = new DataClasses1DataContext();
        private string termid = ConfigurationManager.AppSettings["CurrentTerm"];

        //
        // GET: /CourseManager/

        ////[Authorize]
        //-----
        public ActionResult Index(CancellationToken cancellationToken)
        {
            RegisterSession();
            if (Session["role"].ToString() == "libriadmin")
            {
                //per current term
                //string seeutermid = ConfigurationManager.AppSettings["SEEUCurrentTerm"];
                //ViewBag.termid = seeutermid;

                //prej ne service
                //var seeuService = GetSeeuService();
                //var termsJsonString = seeuService.GetTerms();
                //Term termiaktual = new Term { TermCode = 1169, Description = "FALL- 16/17", AcademicYear = "16/17" };
                //var semesters = seeuService.GetSemesters("1169");
                //DataTable coursesDataTbl = (DataTable)JsonConvert.DeserializeObject(coursesJsonString, (typeof(DataTable)));

                string termid = ConfigurationManager.AppSettings["CurrentTerm"];
                ViewBag.termid = termid;
                //regjistro sesionin nese nuk eshte aktiv
                if (Session["user"] == null) RegisterSession();

                // List courses
                List<CourseViewModel> listaKurseveResult = new List<CourseViewModel>();
                List<Kursi> listaKurseve = db.Kursis.Where(kursi => kursi.termid == termid || kursi.title == "Tutoring").ToList();

                //i merr te gjitha kurset e semestrit aktual
                foreach (Kursi course in listaKurseve)
                {
                    //kontrollo departamentin per dekanet
                    //nese useri i loguar eshte admin ose rektorati futi krejt kurset e semestrit
                    //perndryshe kaperce kurset qe nuk i perkasin departamentit
                    if (Session["dep"].ToString() == "A" || Session["dep"].ToString() == "R")
                    {
                        ////per ALL nxjerrja vetem kurset e CST 
                        //if (courseDepartment != 'C')
                        //    continue;
                    }
                    else
                    {
                        //kaperce kurset qe nuk i perkasin departamentit
                        if (course.depid != Session["dep"].ToString())
                            continue;
                    }

                    //string ownerName = db.GoogleUsers.Where(u => u.GoogleID == course.ownerid).SingleOrDefault().Fullname;
                    CourseViewModel c = new CourseViewModel
                    {
                        Id = course.id,
                        Title = course.title,
                        Owner = course.ownerid,
                        CourseCode = course.coursecode,
                        Link = course.link,
                        //DescriptionHeading = course.DescriptionHeading,
                        UpdateTime = course.updatetime
                    };

                    //merri teachers of the course
                    var courseTeachers = db.CourseDelegations
                        .Join(db.GoogleUsers,
                            del => del.username,
                            guser => guser.Username,
                            (del, guser) => new { delegation = del, GUser = guser })
                        .Where(cc => cc.delegation.kursiid == course.id).ToList();

                    List<LibriTeacher> courseTeachersResult = new List<LibriTeacher>();

                    foreach (var teacher in courseTeachers)
                    {
                        LibriTeacher newt = new LibriTeacher
                        {
                            //GoogleId = teacher.delegation.userid,
                            TeacherName = teacher.GUser.Fullname,
                            TeacherEmail = teacher.GUser.Username + "@" + ConfigurationManager.AppSettings["Domain"]
                        };

                        courseTeachersResult.Add(newt);
                    }
                    c.Teachers = courseTeachersResult;
                    listaKurseveResult.Add(c);
                }
                return View(listaKurseveResult);
            }
            else return RedirectToAction("Index", "Dashboard");
        }

        // GET: /CourseManager/Details/5
        //[Authorize]
        public ActionResult Details(string id)
        {
            if (Session["user"] == null) RegisterSession();
            else
            {
                RegisterClassroomSvc();
                ClassroomService clservice = (ClassroomService)Session["clservice"];
                var getrequest = clservice.Courses.Get(id);
                Course course = getrequest.Execute();
                if (course != null)
                {
                    var c = new LibriCourse
                    {
                        CourseCode = course.Section,
                        Term = course.Section.Substring(course.Section.Length - 3),
                        OwnerId = course.OwnerId,
                        Title = course.Name,
                        CreationTime = DateTime.Parse(course.UpdateTime),
                        Id = course.Id,
                        Link = course.AlternateLink,
                        EnrollmentCode = course.EnrollmentCode
                    };

                    //get teachers
                    var teachersRq = clservice.Courses.Teachers.List(course.Id);
                    ListTeachersResponse teachersLs = teachersRq.Execute();
                    List<LibriTeacher> courseTeachers = new List<LibriTeacher>();
                    if (teachersLs != null)
                        foreach (var teacher in teachersLs.Teachers)
                        {
                            string username = String.Empty;
                            if (teacher.Profile.EmailAddress != null)
                                username = new MailAddress(teacher.Profile.EmailAddress).User;
                            LibriTeacher newt = new LibriTeacher
                            {
                                GoogleId = teacher.UserId,
                                TeacherName = teacher.Profile.Name.FullName,
                                TeacherEmail = teacher.Profile.EmailAddress,
                                Username = username
                            };
                            courseTeachers.Add(newt);
                        }
                    c.Teachers = courseTeachers;

                    //get students
                    var studentsRq = clservice.Courses.Students.List(course.Id);
                    ListStudentsResponse studentsLs = studentsRq.Execute();
                    List<LibriStudent> courseStudents = new List<LibriStudent>();
                    if (courseStudents.Count > 0)
                    {
                        foreach (var student in studentsLs.Students)
                        {
                            string username = new MailAddress(student.Profile.EmailAddress).User;
                            LibriStudent news = new LibriStudent
                            {
                                UserId = student.UserId,
                                StudentName = student.Profile.Name.FullName,
                                StudentEmail = student.Profile.EmailAddress,
                                Username = username
                            };
                            courseStudents.Add(news);
                        }
                        c.Students = courseStudents;
                    }
                    return View(c);
                }
            }
            return RedirectToAction("Index");
        }

        #region CRUD courses

        //
        // GET: /CourseManager/Create
        //[Authorize]
        public ActionResult Create()
        {
            //regjistro sesionin nga SSO nese nuk eshte aktiv
            if (Session["user"] == null) RegisterSession();

            //ViewBag.semestrat = new SelectList(_courseService.GetAllTerms(), "Id", "Description", Int32.Parse(ConfigurationManager.AppSettings["CurrentTerm"]));
            //ViewBag.semestrat = new SelectList(termsLocal, "Value", "Text", Int32.Parse(ConfigurationManager.AppSettings["CurrentTerm"]));

            //build instructors list
            //ViewBag.msuset = new SelectList(_authService.GetInstructors(), "Id", "Username", String.Empty);
            //ViewBag.msuset = new SelectList(instructorsLocal, "Value", "Text", String.Empty);
            return View();
        }

        //
        // POST: /CourseManager/Create

        [HttpPost]
        //[Authorize]
        public ActionResult Create(LibriCourse course)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var c = new Course
                    {
                        DescriptionHeading = course.Title,
                        OwnerId = course.OwnerId + "@" + ConfigurationManager.AppSettings["UNTDomain"],

LibriClassroom/Views/CourseManager/Configure.cshtml
@{
    ViewBag.Title = "Configure";
    //Layout = "~/Views/Shared/_Layout.cshtml";
}

<p style="text-align: center; width: 100%;">
    Please wait while the course is being initialized ...<br/><br/>
    <img src="~/Content/images/ajax-loader.gif" />
</p>

<br/><br/>
<p class="error" style="text-align: center; width: 100%;"></p>

@section scripts{
    <script type="text/javascript">

        $(function () {
            var id;
            $.ajax({
                url: "@Url.Action("InitializeCourse", "CourseManager", new { id = ViewContext.RouteData.Values["id"], area = "Admin" })",
                type: "POST",
                dataType: "json",
                data: "{'id' : '@ViewContext.RouteData.Values["id"]'}",
                contentType: "application/json; charset=utf-8",
                success: function (response) {
                    var d = JSON.stringify(response);
                    //window.setTimeout(function () {
                    //    App.unblockUI("div#content");
                    //    noty({
                    //        text: '<strong>The folder has been successfully created.</strong>',
                    //        type: 'success',
                    //        timeout: 4000
                    //    });
                    //}, 4000);
                    window.location = '@Url.Action("Index", "CourseManager", new { area = "Admin" })?id=' + '@ViewContext.RouteData.Values["id"]' + '&resourceid=' + response + '&title=' + '@ViewBag.Course.Title';
                    //notify client
                    
                },
                error: function (e) {
                    //notify client
                    window.setTimeout(function () {
                        App.unblockUI("div#content");
                        noty({
                            text: '<strong>Unable to initialize course.</strong>',
                            type: 'danger',
                            timeout: 4000
                        });
                    }, 4000);
                }
            });
        });
    </script>
}

LibriClassroom/Views/CourseManager/Create.cshtml
@model LibriClassroom.Models.LibriCourse
@{
    ViewBag.Title = "Add Course";
}

<!-- Breadcrumbs line -->
<div class="crumbs">
    <ul id="breadcrumbs" class="breadcrumb">
        <li>
            <i class="icon-home"></i>
            <a href="@Url.Action("Index", new { controller = "Home" })">Home</a>
        </li>
        <li>
            <a href="@Url.Action("Index", new { controller = "CourseManager" })" title="">Courses</a>
        </li>
        <li class="current">
            <a href="@Url.Action("Create", new { controller = "CourseManager" })" title="">Add</a>
        </li>
    </ul>
</div>
<!-- /Breadcrumbs line -->

<!--=== Page Header ===-->
<div class="page-header">
    <div class="page-title">
        <h3>Add Course</h3>
        <span>@ViewBag.Message</span>
    </div>
</div>
<!-- /Page Header -->


<!--=== Page Content ===-->
<div class="row">
    <div class="col-md-12">
        <div class="widget box">
            <div class="widget-header">
                <h4><i class="icon-reorder"></i>Adding new course</h4>
            </div>
            <div class="widget-content">
                @*<form class="form-horizontal row-border" action="#">*@
                @using (Html.BeginForm("Create", "CourseManager", FormMethod.Post, new { @class = "form-horizontal row-border" }))
                {
                    <div class="form-group">
                        <label class="col-md-2 control-label">Title:</label>
                        <div class="col-md-10">
                            <input type="text" name="Title" class="form-control">
                        </div>
                    </div>
                    
                    <div class="form-group">
                        <label class="col-md-2 control-label">Code:</label>
                        <div class="col-md-10">
                            <input type="text" name="CourseCode" class="form-control">
                        </div>
                    </div>
                    @*
                        
                    <div class="form-group">
                        <label class="col-md-2 control-label">Term:</label>
                        <div class="col-md-10">
                            @Html.DropDownList("Term", ViewBag.semestrat as SelectList, new { @class = "formcontrol" })
                        </div>
                    </div>*@

                    <div class="form-group">
                        <label class="col-md-2 control-label">Teacher Username:</label>
                        <div class="col-md-10">
                            <input type="text" name="OwnerId" class="form-control">
                        </div>
                    </div>

                    <div class="form-actions">
                        <input type="submit" value="Add" class="btn btn-primary pull-right">
                    </div>
                }
                @*</form>*@
            </div>
        </div>
    </div>
</div>
<!-- /Page Content -->

LibriClassroom/Views/CourseManager/Delegate.cshtml
@model IEnumerable<LibriClassroom.ViewModels.RosterViewModel>
@*@using Libri.Web.Ui.GoogleAuth.Infrastructure*@

@{
    ViewBag.Title = "Delegate Users";
    //Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Scripts {
    <script type="text/javascript">
        $(document).ready(function () {
            //===== Autocomplete =====//
            // Using typehead.js-library
            var users = (function () {
                var users = null;
                $.ajax({
                    'async': false,
                    'global': false,
                    'url': "/CourseManager/Autocomplete",
                    'dataType': "json",
                    'success': function (data) {
                        users = data;
                    }
                });
                return users;
            })();
            $('#autocomplete-username').typeahead({
                name: 'autocomplete-username',
                local: users
            });
            $("#btnEnroll").click(function (e) {
                //validimi
                if ($("#autocomplete-username").val() == null || $("#autocomplete-username").val() == '') {
                    alert('Please write a valid user name');
                    return false;
                }
                $('#enrollments').html('<div class="col-md-12"><img src="../../../melon/assets/img/ajax-loading-input.gif" /> Loading...</div>');
                //if (new Date($("#txtDateClose").val()) < new Date($("#txtDateOpen").val())) { alert('The open date of the quiz should be before its closing date.'); return false; }
                //kryeji aksionet pasi lejohet tash
                Enroll();
            });

            function Enroll() {
                var username = $("#autocomplete-username").val();
                var courseid = '@ViewBag.courseid';

                var postValues = "{'username':'" + username + "', 'courseid':'" + courseid + "'}"
                //CreateQuiz(String Activityid, String Username, DateTime DateOpen, DateTime DateClose, int Duration, String Title, String Description, Boolean RandomizeQuestions, Boolean ShowResults, Boolean AllowMultipleRetake, int PassingThreshold, int NegativePoints, int UnansweredPoints, int PointsInGrade)
                App.blockUI("div#content");
                $.ajax({
                    url: "/CourseManager/Delegate",
                    type: "POST",
                    dataType: "json",
                    data: postValues,
                    contentType: "application/json; charset=utf-8",
                    success: function (msg) {
                        if(msg==false)
                        {
                            //notify error client
                            window.setTimeout(function () {
                                App.unblockUI("div#content");
                                noty({
                                    text: '<strong>The user cannot be added or he may be already enrolled for this course.</strong>',
                                    type: 'danger',
                                    timeout: 4000
                                });
                            }, 4000);
                            GetCourseRoster(courseid);
                        } 
                        else
                        {
                            //notify success client
                            window.setTimeout(function () {
                                App.unblockUI("div#content");
                                noty({
                                    text: '<strong>The user was successfully enrolled.</strong>',
                                    type: 'success',
                                    timeout: 4000
                                });
                            }, 4000);
                        }
                        GetCourseRoster(courseid);
                    },
                    error: function (e) {
                        //notify error client
                        window.setTimeout(function () {
                            App.unblockUI("div#content");
                            noty({
                                text: '<strong>The user cannot be added or he may be already enrolled for this course.</strong>',
                                type: 'danger',
                                timeout: 4000
                            });
                        }, 4000);
                        GetCourseRoster(courseid);
                    }
                });
            }
        });

        function DeleteRoster(username) {
            var courseid = '@ViewBag.courseid';

            var postValues = "{'username':'" + username + "', 'courseid':'" + courseid + "'}";
            //CreateQuiz(String Activityid, String Username, DateTime DateOpen, DateTime DateClose, int Duration, String Title, String Description, Boolean RandomizeQuestions, Boolean ShowResults, Boolean AllowMultipleRetake, int PassingThreshold, int NegativePoints, int UnansweredPoints, int PointsInGrade)
            App.blockUI("div#content");
            $.ajax({
                url: "/CourseManager/DeleteRoster",
                type: "POST",
                dataType: "json",
                data: postValues,
                contentType: "application/json; charset=utf-8",
                success: function (msg) {
                    if(msg == true)
                    {
                        var trid = username.split('.').join("");
                        $('#'+ trid).remove();
                        window.setTimeout(function () {
                            App.unblockUI("div#content");
                            noty({
                                text: '<strong>The user was removed successfully.</strong>',
                                type: 'success',
                                timeout: 4000
                            });
                        }, 4000);
                    }
                },
                error: function (e) {
                    window.setTimeout(function () {
                        App.unblockUI("div#content");
                        noty({
                            text: '<strong>The user cannot removed currently.</strong>',
                            type: 'danger',
                            timeout: 4000
                        });
                    }, 4000);
                }
            });
        }
        function GetCourseRoster(courseid)
        {
            $.ajax({
                url: "/CourseManager/GetCourseRoster",
                type: "POST",
                dataType: "json",
                data: "{'courseid':'" + courseid + "'}",
                contentType: "application/json; charset=utf-8",
                success: function (msg) {
                    var list = msg;
                    var disp = "<div class='col-md-12'><table class='table table-striped table-hover'><tr><th> Name </th><th> Username </th><th>Role </th><th></th></tr>";
                    for (i = 0; i < list.length; i++) {
                        //var userid = list[i].UserId;
                        var username = list[i].Username;
                        var trid = username.split('.').join("");
                        var name = list[i].Name;
                        var isTeacher = list[i].IsTeacher;
                        disp += "<tr id='"+ trid +"'><td>";
                        disp += name;
                        disp += "</td><td>";
                        disp += username;
                        disp += "</td><td>";
                        if(isTeacher == true) disp += "Instructor"; else disp += "Student";
                        disp += "</td>";
                        disp += "<td>";
                        disp += "<input type='button' class='btn btn-xs btn-danger' value='Remove' onclick=\"DeleteRoster('" + username + "')\" />";
                        disp += "</td>";
                        disp += "</tr>";
                    }
                    disp += "</table></div>";
                    $("#enrollments").html(disp);
                },
                error: function (e) {
                    window.setTimeout(function () {
                        App.unblockUI("div#content");
                        noty({
                            text: '<strong>Course roster can not be retreived.</strong>',
                            type: 'danger',
                            timeout: 4000
                        });
                    }, 4000);
                }
            });
        }
    </script>
}
<h3>Delegate</h3>

<div class="row">
    <div class="col-md-4">
        <input type="hidden" id="courseid" name="courseid" value="@ViewBag.courseid" />
        <input type="text" id="autocomplete-username" name="autocomplete" class="form-control input-width-xlarge" placeholder="Start typing the username"/>
    </div>
    <div class="col-md-4">
        <input id="btnEnroll" type="button" value="Enroll" class="btn btn-primary" />
    </div>
    <div class="col-md-4">
    </div>
    <div class="col-md-4">
    </div>
</div>
<div id="enrollments" class="row" style="margin-top: 10px;">
    <div class="col-md-12">
    <table class="table table-striped table-hover ">
        <tr>
            <th>
                Name
            </th>
            <th>
                Email
            </th>

            <th>Role
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr id="@item.Username">
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>

                <td>
                    @if(item.IsTeacher == true)
                    {
                        <text>Instructor</text>
                    }
                    else
                    {
                        <text>Student</text> 
                    } 
                </td>
                <td>
                    <input type="button" class="btn btn-xs btn-danger" value="Remove" onclick="DeleteRoster('@item.Username');" />
                </td>
            </tr>
        }

    </table>
</div>
    </div>

LibriClassroom/Views/CourseManager/Delete.cshtml
@model Boolean

@{
    ViewBag.Title = "Delete Course";
}

@if(Model)
{
<h2>Course Deleted successfully!</h2>
}
else {<h2>Course is already Deleted on GC</h2>}
@*@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |*@
        @Html.ActionLink("Back to List", "Index")
    @*</p>
}*@

LibriClassroom/Views/CourseManager/Details.cshtml
@model LibriClassroom.Models.LibriCourse

@{
    ViewBag.Title = "Details";
}
<div class="col-md-12">
    <div class="row"></div>
    <div class="row">
    <div>
        <h2>Course details: @Model.Title</h2>

        <dl style="margin-bottom: 0;">
            <dt>
                @Html.DisplayNameFor(model => model.Id)</dt>

            <dd>
                @Html.DisplayFor(model => model.Id)
            </dd>

            <dt>
                <strong>
                    @Html.DisplayNameFor(model => model.Title)</strong>
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Title)
            </dd>

            <dt>
                <strong>
                    @Html.DisplayNameFor(model => model.CourseCode)</strong>
            </dt>
            <dd>
                <a href="@Model.CourseCode">@Model.CourseCode</a>
            </dd>

            <dt>
                <strong>
                    @Html.DisplayNameFor(model => model.EnrollmentCode)</strong>
            </dt>
            <dd>
                @Html.DisplayFor(model => model.EnrollmentCode)
            </dd>

            <dt>
                <strong>
                    @Html.DisplayNameFor(model => model.Term)</strong>
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Term)
            </dd>

            <dt>
                <strong>
                    @Html.DisplayNameFor(model => model.OwnerId)</strong>
            </dt>
            <dd>
                @Html.DisplayFor(model => model.OwnerId)
            </dd>

            <dt>
                <strong>
                    @Html.DisplayNameFor(model => model.Link)</strong>
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Link)
            </dd>

            <dt>
                <strong>
                    @Html.DisplayNameFor(model => model.CreationTime)</strong>
            </dt>
            <dd>
                @Html.DisplayFor(model => model.CreationTime)
            </dd>

            <dt>
                <strong>Instructors</strong>
            </dt>
            <dd>
                @foreach (var inst in Model.Teachers)
                {
                    <text>@inst.TeacherName</text><br />
                }
            </dd>
            <dt>
                <strong>Students</strong>
            </dt>
            <dd>
                @if (Model.Students != null)
                {
                    foreach (var st in Model.Students)
                    {
                    <text>@st.StudentName - @st.Username</text><br />
                    }
                }
            </dd>
        </dl>
    </div>
    <br />
    <p>
        @Html.ActionLink("Delegate", "Delegate", new { id = Model.Id }) | 
        @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
    
    </p>

    </div>
</div>

LibriClassroom/Views/CourseManager/SyncEverything.cshtml
@model bool
@{
    ViewBag.Title = "SyncEverything";
}

<h2>SyncEverything</h2>
@if (Model)
{
    <p>Everything synched correctly on @DateTime.Now.ToString()</p>
} else {
    <p>Error on: @ViewBag.msg</p>
}

LibriClassroom/Views/CourseManager/Synchronizations.cshtml
@{
    ViewBag.Title = "Synchronizations";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Synchronizations</h2>
<ul class="sub-menu">
    <li>
        <a href="@Url.Action("SyncGoogleUsers", new { controller = "CourseManager" })">
            <i class="icon-user"></i>1. Sync Google Users</a>
    </li>
    <li>
        <a href="@Url.Action("SyncGoogleCourses", new { controller = "CourseManager" })">
            <i class="icon-user"></i>2. Sync Courses CRUD</a>
    </li>
    <li>
        <a href="@Url.Action("SyncGCourseDelegations", new { controller = "CourseManager" })">
            <i class="icon-user"></i>3. Sync Teacher Delegations</a>
    </li>
    <li>
        <a href="@Url.Action("SyncTermCoursesFeeds", new { controller = "CourseManager" })">
            <i class="icon-user"></i>4. Sync Course Feeds</a>
    </li>
    <li>
        <a href="@Url.Action("SyncGenerateALLCoursesStats", new { controller = "CourseManager" })">
            <i class="icon-user"></i>5. Update Course Stats</a>
    </li>
    <li>
        <a href="@Url.Action("SyncGenerateReports", new { controller = "CourseManager" })">
            <i class="icon-user"></i>6. Update Reports</a>
    </li>
    <li>
        <a href="@Url.Action("SyncEverything", new { controller = "CourseManager" })">
            <i class="icon-user"></i>7. Sync All one-by-one</a>
    </li>
</ul>